<a href="https://colab.research.google.com/github/Veerendra-sys/APortfolio/blob/main/300%2Bpython_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lst=[1,2,3,4,5]
for i in lst:
  print(i*i)

1
4
9
16
25


In [ ]:
Sub1=int(input('enter the marks'))
Sub2=int(input('enter the marks'))
Sub3=int(input('enter the marks'))
Sub4=int(input('enter the marks'))
Sub5=int(input('enter the marks'))
Sub6=int(input('enter the marks'))
total=Sub1+Sub2+Sub3+Sub4+Sub5+Sub6
print(total)
avg=total/6
print(avg)

enter the marks10
enter the marks10
enter the marks10
enter the marks10
enter the marks10
enter the marks10
60
10.0


In [ ]:
lst=[3, 4, 6, 7, 9, 10, 2, 8]
new_lst=[]
for i in lst:
  if i>5 and i<10:
    new_lst.append(i)
print(new_lst)
print(sum(new_lst))

[6, 7, 9, 8]
30


In [ ]:
students=["Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George","Faruq","Fahad"]
for i in students:
  if not i.startswith('F'):
    print(i)

Alice
Bob
Charlie
Diana
Ethan
George


In [ ]:
students = ["Charlie","Alice", "Bob",  "Diana", "Ethan","Alice","George","Faruq"]
for i in students:
  if len(i)>5:
    print(i)

Charlie
George


In [ ]:
num1=int(input('ENter the first number'))
num2=int(input('ENter the second number'))
highest=max(num1,num2)
print(highest)

ENter the first number20
ENter the second number5
20


In [ ]:
num1=int(input('ENter the first number'))
num2=int(input('ENter the second number'))
if num1>num2:
  print(num1)
else:
  print(num2)

ENter the first number12
ENter the second number19
19


In [ ]:
n=int(input('enter the number'))
for i in range(0,n+1):
  print('*'*i)

enter the number5

*
**
***
****
*****


In [ ]:
n=int(input('enter the number'))
for i in range(5,0,-1):
  print('*'*i)

enter the number5
*****
****
***
**
*


In [ ]:
n=int(input('enter the number'))
for i in range(0,n+1):
  print(" "*(n-i)+"*"*i)

enter the number5
     
    *
   **
  ***
 ****
*****


In [ ]:
password=input('Enter the password')
if password.isalpha() and password.isalnum():
  print('valid password')
else:
  print('invalid password')

Enter the passwordveerendra
valid password


In [ ]:
number=int(input('ENter the number'))
lst=list(map(int,str(number)))
print(lst)
total=sum(lst)
print(total)

ENter the number12345
[1, 2, 3, 4, 5]
15


In [ ]:
number=int(input('ENter the number'))
lst=list(map(int,str(number)))
print(lst)
remove=lst.clear()
print(lst)

ENter the number123456
[1, 2, 3, 4, 5, 6]
[]


In [ ]:
n=int(input('ENter the total number of rows'))
for i in range(1,n):
  for j in range(i):
    print(chr(64+i+j),end="\t")
  print()

ENter the total number of rows7
A	
B	C	
C	D	E	
D	E	F	G	
E	F	G	H	I	
F	G	H	I	J	K	


In [ ]:
dict1={'name':'veerendra','address':'B.mattam,andhrapradesh','phonenumber':'8074625644'}
print(dict1.values())
dict1['phonenumber']='9989036544'
print(dict1.values())

dict_values(['veerendra', 'B.mattam,andhrapradesh', '8074625644'])
dict_values(['veerendra', 'B.mattam,andhrapradesh', '9989036544'])


In [ ]:
a=int(input('enter the number'))
b=int(input('enter the number'))
c=int(input('enter the number'))
upper=a+b+c*a
print(upper)
lower=b*(2*a+3*b)
print(b)
print(upper/lower)

enter the number1
enter the number2
enter the number6
9
2
0.5625


In [ ]:
character=input('Enter thw character')
vowel='aeiouAEIOU'
if character in vowel:
  print('It containes vowel')
else:
  print('IT is consonent')

Enter thw charactereu
IT is consonent


In [ ]:
import datetime
today=datetime.date.today()
day_name = today.strftime('%A')
print(day_name)
if day_name=='Sunday':
  print('Holiday')
else:
  print('weekday')

Thursday
weekday


In [ ]:
n=int(input('Enter the year number'))
if  n%100!=0 or n%400==0 and n%4==0:
  print('leap year')
else:
  print('not leap year')

Enter the year number2060
leap year


In [ ]:
name='veerendra'
age='23'
print(f"Hello my {name}.your {age} old")

Hwllo my veerendra.your 23 old


In [ ]:
name='veerendra'
age='23'
print("Hello my {}.your {} old" .format(name,age))

Hello my veerendra.your 23 old


In [ ]:
n=int(input('Enter the  number'))
if n%2==0 and n%3==0:
  print('It is divisible by 2 and 3')
else:
  print('It is divisible by 2 and 3')

Enter the  number7
It is divisible by 2 and 3


In [ ]:
def two(num1,num2):
  return max(num1,num2)
print(two(2,13))

13


In [ ]:
colors = ["red", "green", "blue","blue","yellow","red","purple","red" ,"orange", "purple", "red","black", "white"]
count=0
for i in colors:
  count+=i.count('red')
print(count)

4


In [ ]:
colors = ["red", "green", "blue","blue","yellow","red","purple","red" ,"orange", "purple", "red","black", "white"]
print(sorted(colors,reverse=True))

['yellow', 'white', 'red', 'red', 'red', 'red', 'purple', 'purple', 'orange', 'green', 'blue', 'blue', 'black']


In [ ]:
num=int(input('Enter the number'))
print(pow(num,3))

Enter the number3
27


In [ ]:
for i in range(1,11):
  square=pow(i,2)
  cube=pow(i,3)
print(square)
print(cube)
print(square+cube)

100
1000
1100


In [ ]:
for i in range(10,5):
  print(i)

In [ ]:
print(list(range(1,30,2)))

TypeError: 'list' object is not callable

In [ ]:
a=int(input('enter the number'))
b=int(input('enter the number'))
a,b=b,a
print(a)
print(b)

enter the number10
enter the number20
20
10


In [ ]:
from datetime import date
def two_dates(date1,date2):
  diff=date2-date1
  return diff.date
print(two_dates('19-12-2024','25-12-2024'))

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
sentence = "This is a Python string."
word_list = sentence.split()
print(word_list[::-1])

['string.', 'Python', 'a', 'is', 'This']


In [ ]:
from math import factorial
num=factorial(20)
print(num)

2432902008176640000


In [ ]:
from datetime import date
def diff(date1,date2):
  diff=date2-date1
  return diff.days
print(diff('19-12-2024','25-12-2024'))

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
from datetime import datetime, timedelta, date
future_date = now + timedelta(days=7)
print(future_date)

NameError: name 'now' is not defined

In [ ]:
from datetime import datetime

In [ ]:
today=datetime.now().strftime("%Y-%B-%A")
print(today)

2024-December-Saturday


In [ ]:
def percen(num1,num2):
  return(num1/num2)*100
print(percen(100,200))

50.0


In [ ]:
def aver(num1,num2):
  return(num1+num2)/2
print(aver(60,60))

60.0


In [ ]:
first=input('Enter the first name')
last=input('Enter the last name')
print(first+last)

Enter the first nameveerendra
Enter the last nameAmaravathi
veerendraAmaravathi


In [ ]:
Name='Veerendra'
count=" "
for i in Name:
  count+=str(i)
  print(count)

 V
 Ve
 Vee
 Veer
 Veere
 Veeren
 Veerend
 Veerendr
 Veerendra


In [ ]:
A = {3,2,4,5,6,7,8}
B = {4,12,5,1,6,8}
uni=A.union(B)
print(uni)

{1, 2, 3, 4, 5, 6, 7, 8, 12}


In [ ]:
GB=int(input('Enter the gb'))
byte=GB*1000000000
print(byte)

Enter the gb5
5000000000


In [ ]:
def high(lst):
  return max(lst)
print(high([31,22,33,544,5,6,78,82,29,103]))

544


In [ ]:
def per(s):
  square=s*s
  perimeter=s+s+s+s
  return square,perimeter
print(per(5))

(25, 20)


In [ ]:
import random
lst=[
    "red",
    "green",
    "blue",
    "yellow",
    "orange",
    "purple",
    "black",
    "white",
    "pink",
    "brown",
    "gray",
    "cyan",
    "magenta",
    "gold",
    "silver",
    "maroon",
    "olive",
    "lime",
    "teal",
    "navy",
]
random.shuffle(lst)
print(lst)

['gold', 'green', 'orange', 'blue', 'teal', 'lime', 'red', 'purple', 'gray', 'navy', 'brown', 'yellow', 'maroon', 'silver', 'white', 'black', 'olive', 'cyan', 'pink', 'magenta']


In [ ]:
A = {1,12,2,6,7,8}
B = {15,0,1,3,6}
diff=A.difference(B)
print(diff)

{8, 2, 12, 7}


In [ ]:
name='Veerendra'
print(name[1::2])

ernr


In [ ]:
lst=[]
for i in range(10,100):
  if i%5==0 and i%3==0:
    lst.append(i)
print(lst)


[15, 30, 45, 60, 75, 90]


In [ ]:
names = ["Brian", "Ethan", "Dylan", "Megan", "Lauren", "Jason","veer","surend"]
for i in names:
  if i.endswith('n'):
    print(i)


Brian
Ethan
Dylan
Megan
Lauren
Jason


In [ ]:
name=input('Enter the string')
if len(name)==10:
  print('Valid')
else:
  print('Not valid')

Enter the stringveerendra
Not valid


In [ ]:
a=print(list(range(1,20,2)))
b=print(list(range(0,20,2)))
print(sum(a))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


TypeError: 'NoneType' object is not iterable

In [ ]:
lst=[]
for i in range(1,100):
  if i%2==0:
    lst+=i
print(lst)

TypeError: 'int' object is not iterable

In [ ]:
name=input('Enter the file name with extension')
if '.' in name:
  file_extensio=name.split('.')[-1]
  print('File extensions')
else:
  print('Invalid file')

Enter the file name with extensionveerendraaa
Invalid file


In [ ]:
G = 6.674 * 10**-11
m1=int(input('Enter the first object in kg'))
m2=int(input('Enter the second object in kg'))
r=int(input('Enter the distance in meter'))
force=(G*m1*m2)/(r**2)
print(force)

Enter the first object in kg5
Enter the second object in kg10
Enter the distance in meter2
8.3425e-10


In [ ]:
numbers = [7, 42, 32, 14, 5, 61, 7, 8, 92, 10]
print(max(numbers))
print(min(numbers))

92
5


In [ ]:
numbers = [7, 42, 32, 14, 5, 61, 7, 8, 92, 10]
new_lst=[numbers[1],numbers[2],numbers[3],numbers[4],numbers[5],numbers[6],numbers[7]]
print(new_lst)

[42, 32, 14, 5, 61, 7, 8]


In [ ]:
milli=int(input('Enter the millisecond'))
meter=milli/1000
kilo=meter/1000
print(meter)
print(kilo)

Enter the millisecond50000
50.0
0.05


OOPS


In [ ]:
Class Animals:
def __init__(self,name,species):
  self.name=name
  self.species=species
 def speak(self):


SyntaxError: invalid syntax (<ipython-input-2-28f6d37441a2>, line 1)

In [ ]:
class rectangle:
  def __init__(self,lenght,width):
  self.lenght=length
  self.width=width
def perimeter(self):
  return 2*(self.length+self.width)
def area(self):
  return self.lenght*self.width

IndentationError: expected an indented block after class definition on line 1 (<ipython-input-5-ba48e5c9584f>, line 2)

In [ ]:
lst=[1, 2, 3, 4, 5, 6, 7, 8, 9,9,9,9,6,6,6,4,6,8,3,5,2,1,10]
count=0
for i in lst:
  if i in count:
    count[i]+=1
  else:
    count[i]=1
print(count)

TypeError: argument of type 'int' is not iterable

In [ ]:
class Student():
  def __init_(self,name,age,grade):
    self.name=name
    self.age=age
    self.grade=grade
  def display(self):
    print(f"Name:{self.name}")
    print(f"Age:{self.age}")
    print(f"Grade:{self.grade}")
details=Student("Amarava",'23','A')
details.display()

TypeError: Student() takes no arguments

In [ ]:
def square(num):
  prev=pow(num-1,2)
  next=pow(num+1,2)
  return prev,next
print(square(5))

(16, 36)


In [ ]:
lst=[1, 2, 3,[4, 5, 6, 7, 8, 9,2,9,9,5,9],6,6,6,4,6,8,3,5,2,1,10]
new_lst= lst[3][0:11]
count=new_lst.count(5)
print(new_lst)
print(count)

[4, 5, 6, 7, 8, 9, 2, 9, 9, 5, 9]
2


In [ ]:
word=input('ENter the word')
print(word.swapcase())

ENter the wordVeernedrA
vEERNEDRa


In [ ]:
lst=[1, 2, 3,[4, 5, 6, 7, 8, 9,2,9,9,5,9],6,6,6,4,6,8,3,5,2,1,10]
new_lst= lst[3][::]
for i in new_lst:
  print(i)

4
5
6
7
8
9
2
9
9
5
9


In [ ]:
celcuis=int(input('ENter the temperature'))
farenheit=(celcuis*9/5)+32
print(farenheit)

ENter the temperature34
93.2


In [ ]:
import re
user=input(len('password'))
password=re.findall(r"[a-zA-Z0-9+]",user)
print(password)

8Avn@0238
['A', 'v', 'n', '0', '2', '3', '8']


In [ ]:
import re
def check_password(password):
  score=0
  suggest=[]
if len(password)>=8:
  score+=1
else:
  suggest.append('Password should be at least 8 characters long.')
if re.search(r'[a-z]',password):
  score+=1
else:
  suggest.append('Password should contain at least one lowercase letter.')
if re.search(r'[A-Z]',password):
  score+=1
else:
  suggest.append('Password should contain at least one uppercase letter.')
if re.search(r'[0-9]',password):
  score+=1
else:
  suggest.append('Password should contain at least one digit.')
if re.search(r'[@#$%^&+=]',password):
  score+=1
else:
  suggest.append('Password should contain at least one special character.')
return score,suggest

password = input("Input a password: ")
print(check_password(password))

NameError: name 'suggest' is not defined

In [ ]:
my_dict = {"name": "Alice", "age": 30, "city": "New York","clg":"vit"}
print(len(my_dict.keys()))

4


In [ ]:
my_dict = {"name": "Alice", "age": 30, "city": "New York","clg":"vit"}
print(list(my_dict.keys()))
print(list(my_dict.values()))

['name', 'age', 'city', 'clg']
['Alice', 30, 'New York', 'vit']


In [ ]:
array_random = np.random.rand(2, 2)
print("Array with random values:\n", array_random)

Array with random values:
 [[0.27155858 0.35151114]
 [0.74687768 0.41487629]]


In [ ]:
array_random = np.ones((2, 2))
print("Array with random values:\n", array_random)

Array with random values:
 [[1. 1.]
 [1. 1.]]


In [ ]:
my_dict = {
    1: "apple",
    2: "banana",
    3: "cherry",
    4: "date",
    5: "elderberry",
    6: "blackberry"
}
print(max(my_dict.keys()))

6


In [ ]:
my_dict = {"name": "Alice", "age": 30, "city": "New York","clg":"vit"}
my_dict["city"]="Hyderabad"
print(my_dict)

{'name': 'Alice', 'age': 30, 'city': 'Hyderabad', 'clg': 'vit'}


In [ ]:
r=int(input('Enter the radius'))
circumference=2*3.14*r
Area=3.14*r*r
print(circumference)
print(Area)

Enter the radius10
62.800000000000004
314.0


In [ ]:
my_dict={8: 20, 1: 50, 2: 80, 3: 10, 4: 30}
print(sum(my_dict.keys()))
print(sum(my_dict.values()))

18
190


In [ ]:
my_dict = {"name": "Alice", "age": "thirty", "city": "New York","clg":"vit"}
divide=list(my_dict.values())
vowels='aeiouAEIOU'
for i in divide:
  if i in vowels:
    print(i)


In [ ]:
zeros=np.zeros((2,2))
print(zeros)

[[0. 0.]
 [0. 0.]]


In [ ]:
# Multiplication table (from 1 to 10) in Python
num =int(input('wnter the bumber'))
for i in range(1, 11):
   print(num, 'x', i, '=', num*i)

wnter the bumber4
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40


In [ ]:
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
addition=arr1+arr2
print(addition)

[50 70 90]


In [ ]:
matri=np.zeros(4,3).reshape(4,3)
print(matri)

In [ ]:
import numpy as np
arr=np.arange(0,12).reshape(4,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
import numpy as np
arr=np.array([12,3,4,5,6,8,7])
print(list(arr))

[12, 3, 4, 5, 6, 8, 7]


In [ ]:
array = np.array([0, 1, 2, 0, 3])
for i in array:
  print(bool(i))

False
True
True
False
True


In [ ]:
import numpy as np
mat=np.zeros(16).reshape(4,4)
diag=np.fill_diagonal(mat,[6,7,8,9])
print(mat)

[[6. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 8. 0.]
 [0. 0. 0. 9.]]


In [ ]:
details={"name": "Alice", "city": "Wonderland", "fruit": "Apple"}
for i.values() in details:
  print(len(i))

SyntaxError: cannot assign to function call (<ipython-input-24-9743e476e9d1>, line 2)

In [ ]:
my_list = ["apple", "banana", "cherry"]
convert={i:12 for i in my_list}
print(convert)

{'apple': 12, 'banana': 12, 'cherry': 12}


In [ ]:
from os import listdir
list=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
for i in list:
  if i<20 and i>5:
    print(i)

6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
list = ["A", "b", "E", "DCM", "ks", "ssd", "Adf", "EDd"]
new=[i.upper() for i in list]
print(list)

['A', 'b', 'E', 'DCM', 'ks', 'ssd', 'Adf', 'EDd']


In [ ]:
import numpy as np
arr=np.tile([12,3,4,5,6,8,7],2)
print(arr)

[12  3  4  5  6  8  7 12  3  4  5  6  8  7]


In [ ]:
import numpy as np
arr=np.array([12,3,4,5,6,8,7])
arr[arr==12]=9
print(arr)

[9 3 4 5 6 8 7]


In [ ]:
arr=np.array([12,3,4,5,6,8,7])
val=np.append(arr,[23,24,56])
print(val)

[12  3  4  5  6  8  7 23 24 56]


In [ ]:
import numpy as np
import pandas as pd
arr=np.array([12,3,4,5,6,8,7])
ser=pd.Series(arr)
print(ser)

0    12
1     3
2     4
3     5
4     6
5     8
6     7
dtype: int64


In [ ]:
arr=np.array([12,3,4,5,6,8,7])
tran=np.transpose(arr)
print(tran)

[12  3  4  5  6  8  7]


In [ ]:
compre=[i for i in range(1,100)  if i%4==0 or i%5==0]
print(compre)

[4, 5, 8, 10, 12, 15, 16, 20, 24, 25, 28, 30, 32, 35, 36, 40, 44, 45, 48, 50, 52, 55, 56, 60, 64, 65, 68, 70, 72, 75, 76, 80, 84, 85, 88, 90, 92, 95, 96]


In [ ]:
my_dict = {"name": "Alice", "age": 30, "city": "New York","clg":"vit"}
my_dict["univeristy"]=my_dict.pop("clg")
print(my_dict)

{'name': 'Alice', 'age': 30, 'city': 'New York', 'univeristy': 'vit'}


In [ ]:
lst=[9,-2,3,-4,5,6,-8,7]
pos=[i for i in lst if i>0]
neg=[i for i in lst if i<0]
print(pos)
print(neg)

[9, 3, 5, 6, 7]
[-2, -4, -8]


In [ ]:
class Hero:
  def __init__(self,name):
    self.name=name
hero1=Hero('thor')
hero2=Hero('ironman')
hero3=Hero('spiderman')
print(hero1.name)
print(hero2.name)
print(hero3.name)

thor
ironman
spiderman


In [ ]:
email=input('ENter the email')
if '@' in email:
  print('Valid')
else:
  print('invalid')

ENter the emailveeru123gmail.com
invalid


In [ ]:
import sys
print('platform',sys.platform)

platform linux


In [ ]:
import platform

# Get the system/OS name
print("System/OS:", platform.system())

# Get the release version of the OS
print("OS Release Version:", platform.release())

# Get the version of the OS
print("OS Version:", platform.version())

# Get the machine type (e.g., 'x86_64' for 64-bit systems)
print("Machine Type:", platform.machine())

# Get the processor type
print("Processor Type:", platform.processor())

# Get the Python version
print("Python Version:", platform.python_version())


System/OS: Linux
OS Release Version: 6.1.85+
OS Version: #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
Machine Type: x86_64
Processor Type: x86_64
Python Version: 3.10.12


In [ ]:
import tkinter
window=tkinter.TK()
window.title('Hello guys')
window.mainloop()

AttributeError: module 'tkinter' has no attribute 'TK'

In [ ]:
name='VeerendraAmaravathi'
sub=name[9:19][::-1]
print(sub)

ihtavaramA


In [ ]:
import tkinter as tk
from tkinter import messagebox

# Function to handle button click
def on_button_click():
    messagebox.showinfo("Button Clicked", "You clicked the image button!")

# Create the main window
window = tk.Tk()
window.title("Image Button Example")

# Set window size
window.geometry("300x200")

# Load an image (ensure the image is in the same directory or provide the full path)
# The image should be in PNG format for PhotoImage
image = tk.PhotoImage(file="button_image.png")  # Replace with your image file name

# Create a button with the image
image_button = tk.Button(window, image=image, command=on_button_click)

# Place the button in the window
image_button.pack(pady=20)

# Run the application
window.mainloop()


TclError: no display name and no $DISPLAY environment variable

In [ ]:
user=input('enter the string with number')
if user[0].isdigit() and user[-1].isdigit():
  print('USER is valid')
else:
  print('User is invalid')

enter the string with numberveeru123
User is invalid


In [ ]:
my_dict = {"b": 2, "a": 1, "d": 4, "c": 3}
order=dict(sorted(my_dict.items()))
print(order)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
byte=arr.nbytes
print(byte)

40


In [ ]:
lst=[1, 2, 3, 4, 5, 6, 7, 8, 9,9,9,9,6,6,6,4,6,8,3,5,2,1,10]
cou=lst.count(6)
print(cou)

5


In [ ]:
print(np.array(range(1,30,2)))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [ ]:
array=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,9,9,9,6,6,6,4,6,8,3,5,2,1,10])
highest=np.max(array)
print(highest)

10


In [ ]:
class Divi:
  def __init__(self,number):
    self.number=number
  def divisible(self):
    return self.number%5==0

user_input = int(input("Enter a number: "))
check = Divi(user_input)
if check==0:
  print('IT is divisible')
else:
  print('It is not divisible')


Enter a number: 50
It is not divisible


In [ ]:
a=int(input("ENTER THE FIRST NUMBER"))
b=int(input("ENTER THE SECOND NUMBER"))
c=int(input("ENTER THE THIRD NUMBER"))
quadrictic=(-b+(b**2-4*a*c)**0.5)/(2*a)
#uadriti=(-b-())
print(quadrictic)

ENTER THE FIRST NUMBER10
ENTER THE SECOND NUMBER0
ENTER THE THIRD NUMBER10
(6.123233995736766e-17+1j)


In [ ]:
import pandas as pd
num1=int(input("ENTER THE FIRST NUMBER"))
num2=int(input("ENTER THE SECOND NUMBER"))
num3=int(input("ENTER THE THIRD NUMBER"))
num4=int(input("ENTER THE FOURTH NUMBER"))
num5=int(input("ENTER THE FIFTH NUMBER"))
list=[num1,num2,num3,num4,num5]
print(list)

ENTER THE FIRST NUMBER20
ENTER THE SECOND NUMBER40
ENTER THE THIRD NUMBER50
ENTER THE FOURTH NUMBER60
ENTER THE FIFTH NUMBER70
[20, 40, 50, 60, 70]


In [ ]:
alpha_index=list(string
                 .ascii_lowercase[:len(list)])
print(pd.Series(list,index=alpha_index))

AttributeError: type object 'str' has no attribute 'ascii_lowercase'

In [ ]:
import pandas as pd
data = [10, 20, 30, 40, 50]
my_series = pd.Series(data,index=['a','b', 'c', 'd', 'e'])
print(my_series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
data = {'1': "red", '2': "blue", '3': "Orange"}
my_series = pd.Series(data)
print(my_series)

1       red
2      blue
3    Orange
dtype: object


In [ ]:
import getpass
current=getpass.getuser()
print(current)

root


In [ ]:
paragraph=input("Enter the paragraph")
total_chars = len(paragraph)
total_chars_no_space = len(paragraph.replace(" ", ""))
total_words = len(paragraph.split())
total_spaces = paragraph.count(" ")
print("Total characters:", total_chars)
print("Total characters (excluding spaces):", total_chars_no_space)
print("Total words:", total_words)
print("Total spaces:", total_spaces)

Enter the paragraph"The old oak tree stood sentinel at the edge of the meadow, its gnarled branches reaching towards the sky like skeletal fingers."
Total characters: 129
Total characters (excluding spaces): 108
Total words: 22
Total spaces: 21


In [ ]:
sent="The Quick Brown fox Jumps over the Lazy Dog."
Up=sent.upper()
low=sent.lower()
print(Up)
print(low)

THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.
the quick brown fox jumps over the lazy dog.


In [ ]:
A = {3,2,4,5,6,7,8}
B = {4,12,5,1,6,8}
uni=A.union(B)
inte=A.intersection(B)
print(inte)
print(uni)

{8, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 12}


In [ ]:
user=input('Enter the string name')
if len(user)>=5:
  print('The number is valid')
else:
  print('The number is invalid')

Enter the string name1234
The number is invalid


In [ ]:
user=int(input('Enter the number'))
for i in range(1,11):
  print(user,'x',i,'=',user*i)

Enter the number5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [ ]:
lst=[1,2,3,45,60,23,46,12,10,19,14]
first=lst[0]
last=lst[-1]
print(first)
print(last)

1
14


In [ ]:
user=input('Enter the word')
vowels='aeiouAEIOU'
count=0
for i in user:
  if i in vowels:
    count+=1
print(count)

Enter the wordVeerendraAMaravathi
9


In [ ]:
num1=int(input('Enter the first number'))
num2=int(input('Enter the second number'))
square=num1*num2
print(square)

Enter the first number5
Enter the second number5
25


In [ ]:
students = [
    "Aaron Smith",
    "Aanya Patel",
    "John Doe",
    "Jane Roe",
    "Michael Clarke",
    "Anna Brown",
    "Aakash Sharma",
    "Emily Davis",
    "Andrew Johnson",
    "Sophia Wilson"
]
for i in students:
  if i.startswith('AAaa'):
    print(i)

In [ ]:
import math
num=math.factorial(5)
print(num)

120


In [ ]:
lst=["praveen",'Amaravathi']
for i in lst:
  low=i.lower()
if i==low:
  print('It is already lower')
print(i)

Amaravathi


In [ ]:
user_string = input("Enter a string: ")
if " " in user_string:
    print("The string contains spaces.")
else:
    print("The string does not contain spaces.")

Enter a string: Amaravathi Ver
The string contains spaces.


In [ ]:
class Car:
  def __init__(self,make,model,year):
    self.make=make
    self.model=model
    self.year=year
  def display(self):
    return f"{self.year} {self.make} {self.model}"
cars1=Car('toyata','2016','2017')
cars2=Car('audi','1009','2014')
print(cars1.display())
print(cars2.display())

2017 toyata 2016
2014 audi 1009


In [ ]:
class Bankaccount:
  def __init__(self,balance=0):
    self.balance=balance
  def deposit(self,amount):
    self.amount+=amount
    return f"deposit{self.amount} with new balance{self.balance}"
  def withdraw(self,amount):
    if self.balance>amount:
      return "insufficient balance"
    else:
      self.balance-=amount
      return f"Withdrew {amount}. New balance: {self.balance}"
    def check_bal(self,amount):
      return self.balance
account = Bankaccount(100)
print(account.deposit(50))  # Output: Deposited 50. New balance: 150
print(account.withdraw(30))  # Output: Withdrew 30. New balance: 120
print(account.check_balance())

AttributeError: 'Bankaccount' object has no attribute 'amount'

In [ ]:
multiply=lambda x,y:x*y
print(multiply(5,5))

25


In [ ]:
def factorial(n):
  if n==0:
    return 1
  else:
    return factorial(n)*factorial(n-1)
factorial(5)